name = "WarmupHMC"
uuid = "60658175-6863-4866-a322-ab51a11c0cfe"
authors = ["Nikolas Siccha and contributors"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
