name = "WarmupHMC"
uuid = "60658175-6863-4866-a322-ab51a11c0cfe"
authors = ["Nikolas Siccha and contributors"]
version = "0.1.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Pathfinder = "b1d3bc72-d0e7-4279-b92f-7fa5d6d2d454"

[extensions]
WarmupHMCDynamicHMCExt = "DynamicHMC"
WarmupHMCPathfinderExt = "Pathfinder"
WarmupHMCOptimReverseDiffExt = ["Optim", "ReverseDiff"]

[compat]
Distributions = "0.25"
LinearAlgebra = "1"
LogDensityProblems = "2.1.1"
NaNStatistics = "0.6.31"
Random = "1"
UnPack = "1.0.2"
julia = "1.9"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
