project:
  title: "WarmupHMC.jl examples"
  type: website
  output-dir: ../docs/quarto
website:
  sidebar:
    style: "docked"
    contents: auto
format:
  html:
    code-line-numbers: true
jupyter: julia-1.9
execute:
  freeze: auto
  daemon: 3600